name: "tmux-ssh"
shortDesc: "ssh support for kubectl"
longDesc: "tmux-ssh allows users to SSH into Kubernetes nodes by opening a new pane for each matching node"
command: "./tmux-ssh"
flags:
  - name: "selector"
    shorthand: "l"
    desc: "Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)"
  - name: "identity-file"
    shorthand: "i"
    desc: "Selects a file from which the identity (private key) for public key authentication is read"
  - name: "ssh-port"
    shorthand: "p"
    desc: "SSH port"
  - name: "ssh-username"
    shorthand: "u"
    desc: "SSH Username"
  - name: "address-type"
    shorthand: "a"
    desc: "Node address type to query for (e.g. InternalIP/ExternalIP)"
    defValue: "ExternalIP"
